### ISSUE TITLE
Auto complete not triggering if i write @ at the first position.

### ISSUE THREAD

**Issue by ghost** [aurbano/smart-area#24]
Auto complete is not triggering if my text area is empty and i start with @ at first position. 
I attached same [Plunker demo](http://plnkr.co/edit/ABGPRIshuDk3mDcNgZzg). auto complete at first position is not working. it might be regex problem but regex seems working at [Regex101](https://regex101.com). Please correct me if i am doing wrong implementation. i just tried simple demo as of now.

**Comment by ghost** [comment]
hey @aurbano  i see you have changed initialization of lastPosition with -1 and it solved the issue. thanks.

**Comment by aurbano** [comment]
Yes I forgot to mention this issue when adding that fix. As soon as I get a chance I'll update the version and release it for bower and npm.

**Comment by ghost** [comment]
@aurbano  can you please release this change in bower and npm ? It requires to change manually after every build publish. it ill be great help.  Thanks in advance.

**Comment by aurbano** [comment]
@krishnal sorry it took so long! Just released 1.2.0 with the fixes, thanks for reporting this
