### ISSUE TITLE
Angular 2 Support

### ISSUE THREAD

**Issue by jspenc72** [aurbano/smart-area#27]
Any plans to support angular 2 and TS?

**Comment by eusthace811** [comment]
Ohh, yes, any plans? :S

**Comment by aurbano** [comment]
Sorry missed all notifications from this repo for some reason...

Just so other people searching can see this: I'm no longer using this library as I'm no longer working in the project I made it for, and I'm now using React full time so no plans to rewrite for Angular 2 unfortunately.
