### ISSUE TITLE
AGPLv3 makes it nearly impossible to use the library

### ISSUE THREAD

**Issue by thred** [aurbano/smart-area#33]
Hi,

Recently I was searching for a simple way to add autocomplete to a textarea in some proprietary maintenance application of my company. The application will be used internally by a handful of users. smart-area seems to perfectly fit my needs, but unfortunately it's a JavaScript library licensed under (A)GPLv3. 

Using GPLv3 for JavaScript libraries is an ongoing discussion and it's generally considered a bad idea to use it for JS-libs [citation needed]. 

My question is: was it intentionally to use exactly this license, or would LGPLv3 be a better choice?

Another thing is, that the license definition in the package.json is wrong. It should be "AGPL-3.0" not "AGPL-V3" (see https://spdx.org/licenses/). [Webjars](http://www.webjars.org/) refuses to generate a .jar from the lib because of this.

References for the [citation needed]:

http://stackoverflow.com/questions/1239470/restrictions-of-gpl-on-javascript-libraries
http://greendrake.info/#nfy0
https://www.gnu.org/philosophy/javascript-trap.html
...

Thanks for considering,

Manfred

**Comment by mindscratch** [comment]
@aurbano any thoughts on this? Have you considered changing it? or allowing someone else to take over as maintainer?

**Comment by aurbano** [comment]
I'll release a version under MIT
