### ISSUE TITLE
Smart area is not working when js files order change

### ISSUE THREAD

**Issue by VenkatShoreGroup** [aurbano/smart-area#38]
Hi ,
**a.Working scenario of order js files**
1.Jquery 
2.Angularjs
3.smart area.js

**b.Not working scenario of order js files**
1.Angularjs
2.Jquery
3.SmartArea.js

Please suggest in both scenarios it is workable.please send the code also ASAP.
@Morgan-Stanley
Thanks,
Venkat

**Comment by aurbano** [comment]
Not sure if there's anything that can be fixed from the library? I was using requirejs with this and just loaded both jQuery and Angular before...
