### ISSUE TITLE
[FEAT] Autogrow textarea

### ISSUE THREAD

**Issue by amcdnl** [aurbano/smart-area#6]
It would be nice to have an option for it to autogrow as a user put in larger text or returns.

**Comment by aurbano** [comment]
Thanks for the suggestion!
I'm using `smart-area` on a project already and it works nicely with other directives for autogrow such as:
- [angular-elastic](https://github.com/monospaced/angular-elastic)
- [autogrow](https://gist.github.com/thomseddon/4703968)

I'll add this to the Readme so other people can easily add it

**Comment by amcdnl** [comment]
Awesome. Thanks!
